apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: report-ingress
  namespace: arch-analyzer-ia
  labels:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/part-of: arch-analyzer
    app.kubernetes.io/component: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /api/reports
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/reports(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: report-service
                port:
                  number: 8001
