apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: arch-analyzer-ia
  labels:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/part-of: arch-analyzer
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: report-service
  ports:
    - port: 8001
      targetPort: 8001
