name: CD Main Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  ECR_REPOSITORY: arch-analyzer-report
  K8S_NAMESPACE: arch-analyzer-ia
  DEPLOYMENT_NAME: report-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .
          docker tag $ECR_REPOSITORY:${{ github.sha }} $ECR_REPOSITORY:latest
