name: CD Main Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  ECR_REPOSITORY: arch-analyzer-report
  K8S_NAMESPACE: arch-analyzer-ia
  DEPLOYMENT_NAME: report-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
